### ISSUE TITLE
rpush command not found

### ISSUE THREAD

**Issue by HienNguyenAsnet** [rpush/rpush#312] opened 2016-11-04 15:53 UTC
I try install rpush `2.7.0` then run `bundle exec rpush init`. It's raise error
`bundler: command not found: rpush`

**Comment by odedharth** [comment] 2016-12-04 16:34
happened to me on only development from some reason

**Comment by aried3r** [comment] 2016-12-13 14:34
Could you guys specify what exactly you did? How did you install it, do you use spring binstubs or anything special?

**Comment by aried3r** [comment] 2018-07-10 16:52
Closing this since there have been no additional reports of this and I couldn't reproduce it locally.

If anyone is still facing this issue, please open a new issue.

**Closed by aried3r** 2018-07-10 16:52 UTC
Labels: needs-feedback
