### ISSUE TITLE
ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "rpush_apps" does not exist

### ISSUE THREAD

**Issue by rvsingh** [rpush/rpush#281] opened 2016-06-06 06:34 UTC
Rpush: 2.7.0
Rails: 4.2.6

If the database is dropped, then while recreating it, the following error is thrown.

ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "rpush_apps" does not exist

Neither 'rake db:migrate' works nor 'rake db:schema:load'.

Here is the error log

> /Users/rajveershekhawat/.rvm/gems/ruby-2.2.0@rails420/gems/bundler-1.11.2/lib/bundler/shared_helpers.rb:78: warning: Insecure world writable dir /usr in PATH, mode 040777
> rake aborted!
> ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "rpush_apps" does not exist
> LINE 5:                WHERE a.attrelid = '"rpush_apps"'::regclass
>                                           ^
> :               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
>                      pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
>                 FROM pg_attribute a LEFT JOIN pg_attrdef d
>                   ON a.attrelid = d.adrelid AND a.attnum = d.adnum
>                WHERE a.attrelid = '"rpush_apps"'::regclass
>                  AND a.attnum > 0 AND NOT a.attisdropped
>                ORDER BY a.attnum
> /Users/rajveershekhawat/.rvm/gems/ruby-2.2.0@rails420/gems/activerecord-4.2.6/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `async_exec'
> /Users/rajveershekhawat/.rvm/gems/ruby-2.2.0@rails420/gems/activerecord-4.2.6/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in`block in exec_no_cache'
> /Users/rajveershekhawat/.rvm/gems/ruby-2.2.0@rails420/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract_adapter.rb:472:in `block in log'
> /Users/rajveershekhawat/.rvm/gems/ruby-2.2.0@rails420/gems/activesupport-4.2.6/lib/active_support/notifications/instrumenter.rb:20:in`instrument'

**Comment by yanelike** [comment] 2016-06-15 16:26
You can run rpush init and replace the old tables. 
after run rb:migrate.

**Comment by hollowaykeanho** [comment] 2016-07-21 04:29
Any timeline for fixes?

This workaround doesn't make sense for the long run. It works on the development side, but it will have a great impact on the production server.

**Comment by andresfcamacho** [comment] 2017-05-12 21:51
+1 on fixing this. The breaks our CircleCI builds because circle runs:

```
export RAILS_ENV="test"
export RACK_ENV="test"
bundle exec rake db:create db:schema:load --trace
```
which results in same stacktrace.

**Comment by yashka713** [comment] 2018-05-31 09:17
I found new straight thing. I got the same problem as @rvsingh  with `Rails 5.2` and `ruby 2.5.1`.
The error was:
```
rails db:migrate
rails aborted!
ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "rpush_apps" does not exist
LINE 8:                WHERE a.attrelid = '"rpush_apps"'::regclass
```
Also, I added initialize code to the `config\initialializers\rpush.rb`
```
app = Rpush::Apns::App.new
app.name = "my_app"
app.certificate = File.read("/path/to/sandbox.pem")
app.environment = "development"
app.password = "certificate password"
app.connections = 1
app.save!
```
The commenting code in `initialializers` resolved problem.
thx

**Comment by aried3r** [comment] 2019-01-30 14:37
Might be related to https://github.com/rails/rails/issues/32870?

Since nobody else is facing this and I can't reproduce it I'm closing this issue. If anyone is still having this error, having steps to reproduce this would be very welcome!

**Closed by aried3r** 2019-01-30 14:37 UTC

**Comment by artoodeeto** [comment] 2019-02-19 19:03
@hollowaykeanho  I just want to thank you. My boss was behind asking why can't I run dev. lols took me hours. thank you

**Comment by hollowaykeanho** [comment] 2019-02-20 01:31
> @hollowaykeanho I just want to thank you. My boss was behind asking why can't I run dev. lols took me hours. thank you

No problem. Just helping out. =)

**Comment by ChillyHoney** [comment] 2022-03-01 10:46
Okay I found a solution which worked for me. Solution is just 2 comments from above exactly from @yashka713 and @hollowaykeanho. 
I've got errors when I create that `db:reset` and commenting `rpush.rb`. Solution was to comment `rpush.rb` and then do this `db:reset` and voila.

**Comment by enochtamulonis** [comment] 2023-10-04 04:36
I think commenting out the file and deploying would work and you can run the rails db:migrate succesfully no need to reset anything.
The cause for this error is because in the rpush initializer we are creating the app
`app = Rpush::Apnsp8::App.find_or_create_by`
