### ISSUE TITLE
Rpush calls a deprecated ruby method

### ISSUE THREAD

**Issue by jhottenstein** [rpush/rpush#603] opened 2021-03-29 17:36 UTC
Rpush uses a deprecated ruby method Object#=~.  This does not yet cause any issues (the method returns nil which results in the correct behavior) but does spam the logs if you have ruby deprecation warnings turned on.

**To Reproduce**
1. Setup rpush daemon with more than one app connection
2. start server with ruby deprecation warnings enabled: `RUBYOPT='-W:deprecated' bundle exec rpush start`
3. See error in stderr output

**Expected behavior**
Rpush does not call deprecated methods

**Logs and other output**
```
DEPRECATION WARNING: /app/vendor/bundle/ruby/2.7.0/gems/rpush-5.4.0/lib/rpush/daemon/string_helpers.rb:5: warning: deprecated Object#=~ is called on Integer; it always returns nil (called from load at /app/vendor/bundle/ruby/2.7.0/bin/rpush:23)
/app/vendor/bundle/ruby/2.7.0/gems/rpush-5.4.0/lib/rpush/daemon/string_helpers.rb:5:in `=~'
/app/vendor/bundle/ruby/2.7.0/gems/rpush-5.4.0/lib/rpush/daemon/string_helpers.rb:5:in `pluralize' 
/app/vendor/bundle/ruby/2.7.0/gems/rpush-5.4.0/lib/rpush/daemon/app_runner.rb:29:in `start_app' 
/app/vendor/bundle/ruby/2.7.0/gems/rpush-5.4.0/lib/rpush/daemon/synchronizer.rb:20:in `sync_app' 
/app/vendor/bundle/ruby/2.7.0/gems/rpush-5.4.0/lib/rpush/daemon/synchronizer.rb:11:in `block in sync' 
/app/vendor/bundle/ruby/2.7.0/gems/rpush-5.4.0/lib/rpush/daemon/synchronizer.rb:11:in `each' 
/app/vendor/bundle/ruby/2.7.0/gems/rpush-5.4.0/lib/rpush/daemon/synchronizer.rb:11:in `sync' 
/app/vendor/bundle/ruby/2.7.0/gems/rpush-5.4.0/lib/rpush/daemon.rb:85:in `start' 
/app/vendor/bundle/ruby/2.7.0/gems/rpush-5.4.0/lib/rpush/cli.rb:26:in `start' 
/app/vendor/bundle/ruby/2.7.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run' 
/app/vendor/bundle/ruby/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command' 
/app/vendor/bundle/ruby/2.7.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch' 
/app/vendor/bundle/ruby/2.7.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start' 
/app/vendor/bundle/ruby/2.7.0/gems/rpush-5.4.0/bin/rpush:4:in `<top (required)>' 
/app/vendor/bundle/ruby/2.7.0/bin/rpush:23:in `load' 
/app/vendor/bundle/ruby/2.7.0/bin/rpush:23:in `<top (required)>' 
/app/vendor/bundle/ruby/2.7.0/gems/bundler-2.2.11/lib/bundler/cli/exec.rb:63:in `load' 
/app/vendor/bundle/ruby/2.7.0/gems/bundler-2.2.11/lib/bundler/cli/exec.rb:63:in `kernel_load' 
/app/vendor/bundle/ruby/2.7.0/gems/bundler-2.2.11/lib/bundler/cli/exec.rb:28:in `run' 
/app/vendor/bundle/ruby/2.7.0/gems/bundler-2.2.11/lib/bundler/cli.rb:494:in `exec' 
/app/vendor/bundle/ruby/2.7.0/gems/bundler-2.2.11/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run' 
/app/vendor/bundle/ruby/2.7.0/gems/bundler-2.2.11/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command' 
/app/vendor/bundle/ruby/2.7.0/gems/bundler-2.2.11/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch' 
/app/vendor/bundle/ruby/2.7.0/gems/bundler-2.2.11/lib/bundler/cli.rb:30:in `dispatch' 
/app/vendor/bundle/ruby/2.7.0/gems/bundler-2.2.11/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start' 
/app/vendor/bundle/ruby/2.7.0/gems/bundler-2.2.11/lib/bundler/cli.rb:24:in `start' 
/app/vendor/bundle/ruby/2.7.0/gems/bundler-2.2.11/exe/bundle:49:in `block in <top (required)>' 
/app/vendor/bundle/ruby/2.7.0/gems/bundler-2.2.11/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors' 
/app/vendor/bundle/ruby/2.7.0/gems/bundler-2.2.11/exe/bundle:37:in `<top (required)>' 
/app/vendor/bundle/bin/bundle:113:in `load' /app/vendor/bundle/bin/bundle:113:in `<main>'
```
**System configuration (please complete the following information):**
 - OS: Heroku-20 stack (ubuntu)
 - OS version: 20
 - Ruby version: 2.7.2
 - Rails version: 6.1
 - Rpush version: 5.4

**Additional context**
The method is not removed in ruby 3 so this is fine in the short term.

**Comment by benlangfeld** [comment] 2021-03-29 18:47
Duplicate of https://github.com/rpush/rpush/pull/602.

**Closed by benlangfeld** 2021-03-29 18:47 UTC
