### ISSUE TITLE
100% CPU usage on daemon mode

### ISSUE THREAD

**Issue by jlebrijo** [rpush/rpush#178] opened 2015-07-19 09:26 UTC
Hi all,

I observed 100% CPU usage running RPUSH as daemon. I had to restart the process.

The questions are:
- Did anyone experienced this issue? and how did you solve it?
- How can I debug rpush? apart from rpush.log

Thanks!!
Juan

**Comment by ileitch** [comment] 2015-07-19 14:35
Is this happening consistently?

Debugging something like this is very tricky unless it can be reliably reproduced. Does `rpush.log` give any indication?

**Comment by dc85** [comment] 2015-07-23 16:21
Same thing since this morning as well.

log shows normal activity.

**Comment by schmidp** [comment] 2015-07-25 20:29
I have the same problem:

top output (the 104.0 is the cpu time in %):
15968 apps      20   0 1687584 176200   4716 S 104.0  4.4  85196:06 ruby

ps aux output:
apps     15968 72.2  4.3 1687584 176200 ?      Sl   May05 85196:26 rpush | 0 queued | 8 dispatchers

**Comment by allaryin** [comment] 2015-07-30 17:33
Confirmed here as well:
```
deploy    5832 83.5  6.2 358648 129280 ?       Sl   Mar25 152821:21 rpush | 0 queued | 5 dispatchers
```
That's 106 days of cpu time since late March.

Logs are showing nothing interesting happening. In fact, attaching strace shows this:
```
$ sudo strace -p 5832
Process 5832 attached - interrupt to quit
futex(0x7fc4488386a4, FUTEX_WAIT_PRIVATE, 1, NULL^C <unfinished ...>
Process 5832 detached
```

So it appears to be something with how it is waiting for updates?

**Comment by dc85** [comment] 2015-07-30 17:40
Issue was resolved when updated to the newest build

**Comment by allaryin** [comment] 2015-07-30 17:41
Was the update what resolved it, or simply a restart?

**Comment by dc85** [comment] 2015-07-30 17:42
I had to update, then restart

**Comment by allaryin** [comment] 2015-07-30 17:43
Going to let it continue at 2.4 for a bit, if the issue resurfaces, will upgrade. Otherwise, will update here after we upgrade naturally in a few weeks.

**Comment by Benjamin-Dobell** [comment] 2015-10-15 23:05
Seeing this (inside a docker container) with rpush 2.5.0.

**Comment by azhi** [comment] 2015-10-22 10:58
Had seen similar issue inside rpush process.

In my case the cause was another third-party gem (https://github.com/pubnub/ruby), which was silently starting EventMachine in a another thread (Something like `Thread.new{ EM.run }`). One of EventMachine threads was displaying that kind of behavior: 100% cpu load, strace shows endless spamming of `futex` and `gettimeofday`. Solved this by switching to synchronous mode in pubnub, so it does not start EventMachine.

Don't know if it's related, any chance somebody might start EventMachine inside your application processes?

**Comment by aried3r** [comment] 2017-08-31 12:11
Since there have been no new reports for almost two years I'm closing this. Please feel free to open another issue if you are still facing this with 3.0.0.rc1 or newer.

**Closed by aried3r** 2017-08-31 12:11 UTC
Labels: needs-confirmation, needs-feedback

**Comment by armahmoudi** [comment] 2018-06-28 21:00
I have seen this happen for both 100% CPU usage and high memory usage, when using Rpush as a daemon.
