### ISSUE TITLE
Rpush selectively sends notifications. Why?

### ISSUE THREAD

**Issue by liudechris** [rpush/rpush#136] opened 2015-03-08 09:38 UTC
Hi,

I was using RPush v2.0.1 and upgraded to v2.3.2 so that ActiveRecord logs can be stored in a separate rpush.log as opposed to production.log (it was getting difficult to debug).

I started noticing that certain messages will not be sent. E.g., if I send notifications ID #1, 2, 3, 4, 5
I send each notification by Rpush::Apns::Notification.create()
I waited a few seconds between each notification.
In the log I would notice that, e.g.,
[date] [app_name] 1 sent to <device_token>
[date] [app_name] 3 sent to <device_token>
[date] [app_name] 4 sent to <device_token>

In this case, IDs #2 and 5 were not sent (marked in DB as delivered == false).

I tried v2.1.0, v2.2.0, v.2.3.2, and v2.4.0 (latest available). Similar issues. Unfortunately, I cannot try v2.0.1 again to see if the issue exists in this version because I have already migrated the DB to v2.1.0 updates.

I notice a thread open regarding: 
#113 APNS: RPush thinks everything is okay, notification gets marked as delivered, but nothing arrives on phone

I can't tell if my issue is related. Same issue exists for both Apns and Gcm.

Any help appreciated. Thanks.

**Comment by liu6chris** [comment] 2015-03-08 09:51
Update (using v2.1.0):
For Apns, the error messages I got with the un-sent notifications were:
"Unable to deliver notification 948, received error 401 (Unauthorized, check your App auth_key.)"

For Gcm, the error messages I got with the un-sent notifications were:
"undefined method `to_binary' for #<Rpush::Client::ActiveRecord::Gcm::Notification:[some memory address0x000...]>"

For Apns, it appears to be the same error as issue #127 reported earlier.

**Comment by liu6chris** [comment] 2015-03-08 11:35
More update (using v2.4.0):
With v2.4.0 and ActiveRecord, the failure rates are even higher than with v2.1.0.

I switched over to v2.4.0 + Redis:
I noticed that occasionally I do get the same behavior described in #113, but overall the successful delivery rate is much higher.

**Comment by ileitch** [comment] 2015-03-20 18:09
That to_binary error is very odd. Somehow a GCM notification is being processed by the APNs code path. I have no idea how that could possibly happen.

As for the auth_key errors, I need more information and a reproducible test case before I can fix it. I don't have an Android phone to test with.

**Comment by liu6chris** [comment] 2015-03-22 09:32
Thanks Ian for your reply. How can I provide the extra info you need?

**Comment by ileitch** [comment] 2015-03-23 22:32
Does this help you at all? https://github.com/rpush/rpush/issues/127#issuecomment-84232267

**Comment by liu6chris** [comment] 2015-03-24 02:23
Thanks, I tried this already, but I might have switched gems before this as well (Hope you don't mind. I had to quickly switch gems to get push notifications working on my app.) Let me know if I can help further.

**Comment by liu6chris** [comment] 2015-03-25 05:13
Thanks, Ian. I had already tried opening up the IP restriction for GCM earlier.

**Comment by masahirominami** [comment] 2016-01-15 10:52
hello, using 2.5.0 and the same problem happening with us.

APNs message is made to push_notifications table, but the error says:

undefined method `to_binary' for #<Rpush::Client::ActiveRecord::Gcm::Notification:0x00000005fe48b8> 

is there any solution / workaround for this issue ?

Thank you in advance.

**Comment by masahirominami** [comment] 2016-01-15 13:59
update:

it seems we found problem with us.
we set up connection for GCM app to '5' as well as APNs.
setting both to '1' solved the problem for now.
we will try setting multiple connection for APNs and see if everything is ok.

**Comment by masahirominami** [comment] 2016-01-16 02:47
we are very sorry but PLEASE IGNORE ABOVE COMMENT.

it has nothing to do with the problem it seems, we are still having the same situation.
we have 2 environments, and both had the same problem - last night we restarted rpush on oner server and it is working somehow ok now - but the other server is having this problem and none of our notification is being sent - the same error...

**Comment by masahirominami** [comment] 2016-01-21 02:56
UPDATE: we found out that our program had a bug that pushes GCM notifications to APNS app.
after fixing the problem, so far push is working fine.

thank you.

**Comment by nathanpaul** [comment] 2017-03-16 15:12
Any updates on this?

**Comment by aried3r** [comment] 2019-02-14 15:24
Hey! Thanks for reporting the issue and everyone's feedback! Since there haven't been any new reports for some time I'm closing this issue. Please feel free to open a new issue if you're still experiencing this issue with the latest Rpush release.

**Closed by aried3r** 2019-02-14 15:24 UTC
