### ISSUE TITLE
APNS alerts with content_available not displayed

### ISSUE THREAD

**Issue by virusman** [rpush/rpush#659] opened 2023-10-10 10:24 UTC
**Describe the bug**
 APNS messages containaing _both_ alert and `content-available` are not being rendered on devices

**To Reproduce**
1. Set up an APNS (p8) app
2. Send a message that contains both an alert and `content-available` set to 1.
3. Observe that no message is displayed.
If `content-available` is not set, it will work fine.

**Expected behavior**
Message should be displayed.

**Logs and other output**
Not applicable

**System configuration (please complete the following information):**
 - OS: macOS
 - OS version: 14.0
 - Ruby version: 3.1.4
 - Rails version: 7.0.4
 - Rpush version: 7.0.1

**Additional context**
The problem is this part of code, where the push type is explicitly set to `background` when `content-available` is set: 
<img width="735" alt="image" src="https://github.com/rpush/rpush/assets/932048/0103ae6f-c766-4f2a-9816-e4708100778e">
 It should not be set to background if alert is present.

**Comment by benlangfeld** [comment] 2024-09-05 20:31
Looks like I lost track of this in the past: https://github.com/rpush/rpush/pull/596#issuecomment-1410495882

**Comment by benlangfeld** [comment] 2024-09-05 20:32
This is a duplicate of https://github.com/rpush/rpush/issues/647

**Closed by benlangfeld** 2024-09-05 20:32 UTC
Labels: APNs
